## **Basic Model using Sklearn**

In [44]:
# import libaraires
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler
from sklearn.linear_model import LinearRegression

In [45]:
# import dataset
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [46]:
# preprocess the data
# scaler = StandardScaler()
# df[['total_bill', 'tip']] = scaler.fit_transform(df[['total_bill', 'tip']])

In [47]:
# seperate the feature X and the target/labels y
X = df[['total_bill']]
y = df['tip']

In [48]:
# train test split the data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [49]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
imputer.fit_transform(X_train)

array([[14.15],
       [ 9.78],
       [13.  ],
       [ 9.94],
       [30.06],
       [10.34],
       [16.99],
       [17.89],
       [12.02],
       [11.17],
       [20.08],
       [27.28],
       [35.83],
       [17.47],
       [15.98],
       [22.75],
       [11.87],
       [10.34],
       [21.01],
       [15.77],
       [16.27],
       [16.45],
       [40.55],
       [22.76],
       [24.06],
       [ 7.51],
       [ 7.56],
       [16.97],
       [16.4 ],
       [16.82],
       [22.42],
       [10.33],
       [22.49],
       [ 7.25],
       [13.81],
       [16.21],
       [16.93],
       [26.86],
       [ 8.77],
       [29.85],
       [34.83],
       [22.23],
       [13.42],
       [12.6 ],
       [ 5.75],
       [20.69],
       [13.13],
       [35.26],
       [14.48],
       [19.65],
       [15.48],
       [16.47],
       [11.02],
       [13.37],
       [50.81],
       [13.27],
       [17.59],
       [ 7.74],
       [16.58],
       [12.48],
       [11.38],
       [14.07],
       [

In [50]:
# call the model 
model = LinearRegression()

In [51]:
# train the model 
model.fit(X_train, y_train)

LinearRegression()

In [52]:
model.predict([[15]])

c:\Users\asada\miniconda3\envs\python\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.48856281])

In [53]:
# prediction
y_pred = model.predict(X_test)

In [54]:
# evaluation the model
from sklearn.metrics import mean_squared_error, r2_score
print('MSE: ', mean_squared_error(y_test, y_pred))
print('R2: ', r2_score(y_test, y_pred))

MSE:  1.3247202763859776
R2:  0.4486766201343517


## Save and load a model

In [55]:
# save the model 
import pickle 
pickle.dump(model, open('./saved_models/01_model.pkl', 'wb'))

In [56]:
# load the model
import pickle
model_load = pickle.load(open('./saved_models/01_model.pkl', 'rb'))

In [57]:
model_load.predict([[15]])

c:\Users\asada\miniconda3\envs\python\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.48856281])