## **Linear Algebra**

In [1]:
import numpy as np
 

In [2]:
list1 = [1,2,3]
list2 = [10,20,30]

vector1 = np.array(list1)
vector2 = np.array(list2)

print('Horizontal Vector')
print(vector1)

print('Vertical Vector')
print(vector2)

Horizontal Vector
[1 2 3]
Vertical Vector
[10 20 30]


In [3]:
addition = vector1 + vector2
print('Vector Addition    : ' + str(addition))

subtraction = vector1 - vector2
print('Vector Subtraction   : ' + str(subtraction))

multiplication = vector1 * vector2
print('Vector Multiplication    : ' + str(multiplication))

scaler = 2
print('Scaler   : ' + str(scaler))
scaler_mul = vector1 * scaler
print('Scaler Multiplication    : ' + str(scaler_mul))

division = vector1 / vector2
print('Vector Division  : '+ str(division))

Vector Addition    : [11 22 33]
Vector Subtraction   : [ -9 -18 -27]
Vector Multiplication    : [10 40 90]
Scaler   : 2
Scaler Multiplication    : [2 4 6]
Vector Division  : [0.1 0.1 0.1]


In [4]:
# Dot Product
dot_product = vector1.dot(vector2)
print('Dot Product  : '+ str(dot_product))

# Cross Product 
cross_product = np.cross(vector1, vector2)
print('Cross Product    : '+ str(cross_product))

Dot Product  : 140
Cross Product    : [0 0 0]


In [5]:
# Vector Norm l1
from numpy.linalg import norm

arr = np.array([1,3,5])
l1 = norm(arr,1)
print(l1)

9.0


In [6]:
# l2
arr = np.array([1,3,5])
l2 = norm(arr, 2)
print(l2)

5.916079783099616


In [7]:
from numpy import inf
v = np.array([1,3,5])
vecmax = norm(v, inf)
print(vecmax)


5.0


In [8]:
# Vector Projection 

a = np.array([1,2,3])
b = np.array([5,6,2])

# finding norm of vector b
b_norm = np.sqrt(sum(b**2))

# finding dot product using np.dot()
proj_of_a_on_b = (np.dot(a,b)/b_norm**2)*b

print('Projection of vector a on b is : ' ,(proj_of_a_on_b))

Projection of vector a on b is :  [1.76923077 2.12307692 0.70769231]


In [9]:
a = np.array([1,2,3])
b = np.array([5,6,2])

a_norm = np.sqrt(sum(a**2))

proj_of_b_on_a = (np.dot(a,b)/a_norm**2)*a

print('Projection of vector b on a is : ' ,(proj_of_b_on_a))

Projection of vector b on a is :  [1.64285714 3.28571429 4.92857143]


In [10]:
# Linear Combination of Vector

x = np.array([[0,0,1],
              [0,1,0],
              [1,0,0]])
y = ([3.65, 1.55, 3.42])
scaler = np.linalg.solve(x, y)
scaler

array([3.42, 1.55, 3.65])

In [11]:
import sympy

matrix = np.array([
    [0,5,1],
    [0,10,0]
])

_, indexes = sympy.Matrix(matrix).T.rref()

print(indexes)

(0, 1)


In [12]:
print(matrix[indexes, :])

[[ 0  5  1]
 [ 0 10  0]]


In [13]:
if len(indexes) == 2:
    print('Linearly Independent')
else:
    print('Linearly Dependent')

Linearly Independent


In [14]:
x = np.array([
    [1,2],
    [4,5]
])
y = np.array([[7,8], [9,10]])

In [15]:
print('The element wise addition of matrix is : ')
print(np.add(x,y))

print('The element wise subtraction of matrix is : ')   
print(np.subtract(x,y))

print('The element wise multiplication of matrix is : ')
print(np.multiply(x,y))

print('The element wise division of matrix is : ')
print(np.divide(x,y))

print('The element wise square root of matrix is : ')
print(np.sqrt(x))

print('The summation of all matrix element is : ')
print(np.sum(y))

print('The column wise summation of all matrix element is : ')
print(np.sum(y,axis=0))

print('The row wise summation of all matrix element is : ')
print(np.sum(y,axis=1))

print('The transpose of given matrix is : ')
print(x.T)

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
The element wise square root of matrix is : 
[[1.         1.41421356]
 [2.         2.23606798]]
The summation of all matrix element is : 
34
The column wise summation of all matrix element is : 
[16 18]
The row wise summation of all matrix element is : 
[15 19]
The transpose of given matrix is : 
[[1 4]
 [2 5]]


In [16]:
# Vectors as 1D Arrays

a  = np.array([1,2,3])
b  = np.array([4,5,6])

print('a = ', a)
print('b = ', b)
print('inner : ', np.inner(a,b))
print('dot : ', np.dot(a,b))

a =  [1 2 3]
b =  [4 5 6]
inner :  32
dot :  32


In [17]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6,7],[8,9,10]])

c = np.matrix([[1,2],[3,4]])
d = np.matrix([[5,6,7],[8,9,10]])

print('dot product of two ndarray objects : ')
print(np.dot(a,b))

print('dot product of two matrix objects : ')   
print(np.dot(c,d))

dot product of two ndarray objects : 
[[21 24 27]
 [47 54 61]]
dot product of two matrix objects : 
[[21 24 27]
 [47 54 61]]


In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.matrix([[1,2],[3,4]])
d = np.matrix([[5,6],[7,8]])

print('operation on on ndarray objects (element wise) : ')
print(a*b)

print('operation on on matrix objects (same as np.dot()) : ')
print(c*d)

operation on on ndarray objects (element wise) : 
[[ 5 12]
 [21 32]]
operation on on matrix objects (same as np.dot()) : 
[[19 22]
 [43 50]]
