In [1]:
import numpy as np

In [2]:
v = np.array([1, -1, 2])
w = np.array([2, 5, 2])

In [3]:
# additional vector
print(v+w)

[3 4 4]


In [4]:
# Subtract vector
print(v-w)

[-1 -6  0]


In [5]:
# Scaler Mult:
print(3*v)

[ 3 -3  6]


In [6]:
# Length
print(np.linalg.norm(v))

2.449489742783178


In [7]:
# Dot Product of Vectors
print(np.dot(v, w))

1
