In [1]:
import numpy as np

In [3]:
p = np.array([[1,7],[2,1],[3,2]])
print(p)

[[1 7]
 [2 1]
 [3 2]]


In [4]:
q = np.array([[1,1],[1,-1],[1,0]])
print(q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [5]:
#addition matrix
c1 = np.add(p, q)
print(c1)

[[2 8]
 [3 0]
 [4 2]]


In [7]:
# multiplication of matrix
r = np.array([[1,3,1], [1,0,1]])
c2 = np.dot(p,r)
print(c2)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [9]:
# Determinant
det = np.linalg.det(c2)
print(det)
s2 = np.linalg.inv(c2)  # the determinant of c2 is zero so its inverse will be null

0.0


LinAlgError: Singular matrix

In [10]:
m = np.array([[1,-1],[2,3]])
print(np.linalg.inv(m))

[[ 0.6  0.2]
 [-0.4  0.2]]
