# **Numpy**

In [1]:
import numpy as np

> ## What is an array?

### **Answer**
An array is a data structure that stores a collection of data values of the same type. Some key points about arrays:

- Elements/items: An array contains multiple elements/items, each with its own index number. Elements can be any data type (numbers, strings, etc).

- Dimensions: Arrays can be one-dimensional (1D), two-dimensional (2D), three-dimensional (3D) and so on. Each additional dimension is called a dimension.

- Indexing: Elements in an array are accessed via numeric indices, which are the position numbers of each element. Indexing starts from 0. 

- Contiguous memory locations: All elements of an array are stored in adjacent memory locations. This allows for fast random access of elements.

- Fixed size: Once created, arrays have a fixed size that can't be changed. Additional elements can't be added later. 

- Homogeneous data type: All elements in an array must be of the same data type (e.g. integers, floats). Heterogeneous types are not allowed.

- Fast access: Since elements are stored contiguously, any element can be accessed directly in O(1) time using its index.

Common examples include lists, vectors, matrices, images. Arrays are a fundamental data structure in programming languages like C/C++ and data analysis tools like NumPy in Python.

In [2]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [3]:
a2 = a[np.newaxis, : ]

print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [4]:
a3 = a2[np.newaxis, : ]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

> **Assignment**
## Why do have 1D, 2D or 3D arrays and where we need them in Data Science?

### **Answer**
> Here are the key points about 1D, 2D, and 3D arrays in Jupyter notebooks for data science:

- 1D arrays are useful for time series, signals and single variable datasets.

- 2D arrays represent images with pixels as elements and are used extensively in computer vision tasks. 

- 3D arrays handle volumetric image data and temporal datasets with an extra dimension like videos. 

- NumPy library allows easy creation and manipulation of multi-dimensional arrays in Jupyter.

- Images, videos can be directly loaded as 2D and 3D arrays from files for analysis.

- Neural networks and CNNs require input data to be arranged as matrices/tensors for matrix operations.

- Intermediate data formats like resized images are 2D arrays transformed from original files.  

- Visualization of array data is simple using matplotlib for plots and images in a notebook.

- Operations like convolutions, matrix math benefit from compact array representation of data.

So in summary, 1D, 2D and 3D arrays provide a natural way to represent different types of structured data for analysis and modeling in Jupyter notebooks.

---

### Creating an Array

In [5]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([(1,2,3,4,5,6,7),(4,5,6,7,8,9,10)])

In [6]:
a.shape

b.shape

(2, 7)

In [7]:
zeros = np.zeros((12,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
#creating a identity matrix
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Array Attributes

In [10]:
b.shape

(2, 7)

In [11]:
b.ndim

2

In [14]:
len(b)

2

In [12]:
b.size

14

### Operation

In [15]:
g = a - b 
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [16]:
h = np.add(a, b)
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [17]:
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36, 49])