## Numpy Day 2

In [1]:
import numpy as np

In [2]:
empty = np.empty((2,3))
print(empty)

[[0.00000000e+000 0.00000000e+000 1.65681564e-056]
 [2.22425183e-133 3.58611778e-306 3.05652234e-037]]


In [3]:
# Arrays of even numbers
even = np.arange(0,22,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
# Arrays of odd numbers
odd = np.arange(1,22,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [5]:
lin = np.linspace(0,10,num=8)
lin

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [6]:
arr = np.array([2,1,5,7,4,3,6,8])
arr
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
# concatenation both arrays
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
x = np.array([[1,5], [7,1]])
y = np.array([[2,4], [8,2]])

z = np.concatenate((x, y), axis=1)
z

array([[1, 5, 2, 4],
       [7, 1, 8, 2]])

In [9]:
z.ndim

2

In [10]:
# create 3D array
array_example = np.array(
                            [[[0,1,2,3],
                           [4,5,6,7]],

                           [[0,1,2,3],
                            [4,5,6,7]],

                            [[0,1,2,3],
                             [4,5,6,7]]]
                        )

array_example.ndim

3

In [13]:
a = np.array([[[0,1,2,3]], [[4,5,6,7]], [[9,8,7,6]]])
a.shape

(3, 1, 4)

In [14]:
a = a.reshape(6,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [9, 8],
       [7, 6]])

In [15]:
a = np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [17]:
a[np.newaxis, :].shape

(1, 8)

### Indexing and slicing

In [18]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
a[2:5]

array([3, 4, 5])

In [23]:
a[-4:-2]

array([4, 5])