In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.7233, 0.6746, 0.2769],
        [0.3094, 0.8790, 0.0099]])

In [8]:
# use of seed
torch.rand(2,3)

tensor([[0.4271, 0.2821, 0.8564],
        [0.9675, 0.6601, 0.8621]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
# other ways

# arange
print("using arange ->", torch.arange(0,10))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 3))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])


## Tensor Shapes

In [29]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
x.shape

torch.Size([2, 3])

In [31]:
torch.empty_like(x)

tensor([[124126592, 124147280,         0],
        [        0,         1,         0]])

In [32]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [33]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [37]:
# find data type
x.dtype

torch.int64

In [38]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [39]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [40]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [47]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [58]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

### 2. Element wise operation

In [59]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [65]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

In [66]:
c = torch.tensor([1, -2, 3, -4])

In [67]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [68]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [69]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [70]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [71]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [72]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [73]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 9., 5.],
        [7., 3., 9.]])

In [76]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([14., 19.])

In [78]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([3.5000, 6.0000, 7.0000])

In [79]:
# median
torch.median(e)

tensor(5.)

In [80]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [81]:
# product
torch.prod(e)

tensor(0.)

In [82]:
# standard deviation
torch.std(e)

tensor(3.5637)

In [83]:
# variance
torch.var(e)

tensor(12.7000)

In [84]:
# argmax
torch.argmax(e)

tensor(1)

In [85]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [86]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 0, 5],
        [7, 5, 9]])
tensor([[9, 7],
        [5, 9],
        [8, 9]])


In [87]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 76,  73],
        [160, 175]])

In [88]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [94]:
# transpose
torch.transpose(f, 0, 1)

tensor([[4, 7],
        [0, 5],
        [5, 9]])

In [95]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[7., 9., 2.],
        [6., 7., 7.],
        [8., 3., 6.]])

In [96]:
# determinant
torch.det(h)

tensor(251.)

In [97]:
# inverse
torch.inverse(h)

tensor([[ 0.0837, -0.1912,  0.1952],
        [ 0.0797,  0.1036, -0.1474],
        [-0.1514,  0.2032, -0.0199]])

### 5. Comparison operations

In [98]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 5, 5],
        [0, 4, 3]])
tensor([[8, 8, 3],
        [3, 5, 0]])


In [99]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [100]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[6., 4., 0.],
        [8., 4., 7.]])

In [101]:
# log
torch.log(k)

tensor([[1.7918, 1.3863,   -inf],
        [2.0794, 1.3863, 1.9459]])

In [102]:
# exp
torch.exp(k)

tensor([[4.0343e+02, 5.4598e+01, 1.0000e+00],
        [2.9810e+03, 5.4598e+01, 1.0966e+03]])

In [103]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 2.0000, 0.0000],
        [2.8284, 2.0000, 2.6458]])

In [104]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9820, 0.5000],
        [0.9997, 0.9820, 0.9991]])

In [105]:
# softmax
torch.softmax(k, dim=0)

tensor([[1.1920e-01, 5.0000e-01, 9.1105e-04],
        [8.8080e-01, 5.0000e-01, 9.9909e-01]])

In [106]:
# relu
torch.relu(k)

tensor([[6., 4., 0.],
        [8., 4., 7.]])

## Inplace Operations

In [107]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.5548, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])
tensor([[0.0103, 0.9516, 0.2855],
        [0.2324, 0.9141, 0.7668]])


In [108]:
m.add_(n)

tensor([[0.5650, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

In [109]:
m

tensor([[0.5650, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

In [110]:
n

tensor([[0.0103, 0.9516, 0.2855],
        [0.2324, 0.9141, 0.7668]])

In [111]:
torch.relu(m)

tensor([[0.5650, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

In [112]:
m.relu_()

tensor([[0.5650, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

In [113]:
m

tensor([[0.5650, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

## Copying a Tensor

In [114]:
a = torch.rand(2,3)
a

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [115]:
b = a

In [116]:
b

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [117]:
a[0][0] = 0

In [118]:
a

tensor([[0.0000, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [119]:
b

tensor([[0.0000, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [120]:
id(a)

133055717071888

In [121]:
id(b)

133055717071888

In [122]:
b = a.clone()

In [123]:
a

tensor([[0.0000, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [124]:
b

tensor([[0.0000, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [125]:
a[0][0] = 10

In [126]:
a

tensor([[10.0000,  0.4393,  0.2243],
        [ 0.8935,  0.0497,  0.1780]])

In [127]:
b

tensor([[0.0000, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [128]:
id(a)

133055717071888

In [129]:
id(b)

133055719057616