In [1]:
from sklearn.datasets import make_classification
import torch

In [17]:
X, y = make_classification(
    n_samples=10,
    n_features = 2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)
print(X)
print('-'*80)
print(y)

[[ 1.06833894 -0.97007347]
 [-1.14021544 -0.83879234]
 [-2.8953973   1.97686236]
 [-0.72063436 -0.96059253]
 [-1.96287438 -0.99225135]
 [-0.9382051  -0.54304815]
 [ 1.72725924 -1.18582677]
 [ 1.77736657  1.51157598]
 [ 1.89969252  0.83444483]
 [-0.58723065 -1.97171753]]
--------------------------------------------------------------------------------
[1 0 0 0 0 1 1 1 1 0]


In [24]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

<ipython-input-24-b05a7ba812dd>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)
<ipython-input-24-b05a7ba812dd>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, dtype=torch.long)


In [25]:
from torch.utils.data import DataLoader, Dataset

In [26]:
class customdataset(Dataset):

  def __init__(self, feature, label):
    self.features = feature
    self.labels = label

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]


In [27]:
dataset = customdataset(X, y)

In [28]:
len(dataset)

10

In [29]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [30]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [31]:
for batch_feature, batch_label in dataloader:
  print(batch_feature)
  print(batch_label)
  print('-'*50)

tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [ 1.7774,  1.5116]])
tensor([0, 1])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-0.7206, -0.9606]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-1.9629, -0.9923]])
tensor([1, 0])
--------------------------------------------------
